### ISSUE TITLE
[Ember 2.3]: DEPRECATION: Using the injected `container` is deprecated. 

### ISSUE THREAD

**Issue by tschoartschi** [simplabs/ember-simple-auth#857]
Hi!

I upgraded to Ember 2.3 and I get the following deprecation: 

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://localhost:4200/app/assets/vendor.js:15523:7)
        at raiseOnDeprecation (http://localhost:4200/app/assets/vendor.js:15433:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/app/assets/vendor.js:15523:7)
        at invoke (http://localhost:4200/app/assets/vendor.js:15539:7)
        at deprecate (http://localhost:4200/app/assets/vendor.js:15492:32)
        at Object.deprecate (http://localhost:4200/app/assets/vendor.js:25501:37)
        at Object.defineProperty.get (http://localhost:4200/app/assets/vendor.js:10953:26)
        at _bindToAuthenticatorEvents (http://localhost:4200/app/assets/vendor.js:173516:31)
```
When I step through the stacktrace it points to the following places:

```
(anonymous function)         application-route-mixin.js:89
(anonymous function)         application-route-mixin.js:83
setupSessionRestoration      setup-session-restoration.js:7
initialize                   ember-simple-auth.js:5
``` 

```
restore                    internal-session.js:53
beforeModel                setup-session-restoration.js:17
setupSessionRestoration    setup-session-restoration.js:7
``` 

```
_bindToAuthenticatorEvents  internal-session.js:150
_setup                      internal-session.js:89
(anonymous function)        internal-session.js:64
``` 

```
authorize        session.js:209
exports.default._ember.default.Mixin.create.ajaxOptions.hash.beforeSend        data-adapter-mixin:76
``` 

Hope this helps. Thanks

**Comment by marcoow** [comment]
PR would be great - should be easily doable with https://github.com/rwjblue/ember-getowner-polyfill

**Comment by tschoartschi** [comment]
@marcoow okay, I'll give it a try :smiley: but I'm not sure if I can find all the appearances since I'm not too familiar with the ```ember-simple-auth``` internals

**Comment by jcope2013** [comment]
are you running against simple auth master? a lot of them have been fixed but there is still one outstanding https://github.com/simplabs/ember-simple-auth/pull/822

in you package.json
```  "ember-simple-auth": "git://github.com/simplabs/ember-simple-auth.git" ```

``` rm -rf node_modules/ember-simple-auth && npm install ```

**Comment by tschoartschi** [comment]
@jcope2013 no I'm not on master. I just realized when I updated this morning to Ember 2.3. Does it make sense to create a PR or is is already almost solved?

**Comment by 2468ben** [comment]
I'm using master, and the simple auth test helpers are also giving me deprecation messages since they're using `app.__container__.lookup`. So whoever digs in to squash the deprecations, check there too (I couldn't figure out how access the app instance in the helpers)

**Comment by agarcia17** [comment]
im using master and still getting this deprecation on ember 2.3

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
            at HANDLERS.(anonymous function) (http://127.0.0.1:4200/assets/vendor.js:16693:7)
        at raiseOnDeprecation (http://127.0.0.1:4200/assets/vendor.js:16603:12)
        at HANDLERS.(anonymous function) (http://127.0.0.1:4200/assets/vendor.js:16693:7)
        at invoke (http://127.0.0.1:4200/assets/vendor.js:16709:7)
        at deprecate (http://127.0.0.1:4200/assets/vendor.js:16662:32)
        at Object.deprecate (http://127.0.0.1:4200/assets/vendor.js:26671:37)
        at Object.defineProperty.get (http://127.0.0.1:4200/assets/vendor.js:12123:26)
        at Function.ClassMixinProps._lazyInjections (http://127.0.0.1:4200/assets/vendor.js:47114:19)
        at instantiate (http://127.0.0.1:4200/assets/vendor.js:12078:34)
```

**Comment by robclancy** [comment]
It is getting pretty annoying having to install specific commits as versions because releases aren't being tagged. Not to mention working with latest versions of ember should happen fast and never do.

When I have time will have to roll my own code instead of use this.

**Comment by tschoartschi** [comment]
@robclancy I don't think there is a ```release```. I think they are still working on the deprecations.

I could contribute/help a little bit but I don't know how to start or if it is still necessary to help.

**Comment by jcope2013** [comment]
there is 2 failing tests for the PR to fix the last deprecation, I could use some help trying to fix them

https://github.com/simplabs/ember-simple-auth/pull/822
https://travis-ci.org/simplabs/ember-simple-auth/builds/104554171

**Comment by yurifrl** [comment]
I believe this will solve the problem, it worked for me
https://github.com/yurifrl/ember-simple-auth/commit/bb121825bba872aa4f86c7100782cde9bca03b85

**Comment by shailendragnit** [comment]
Still getting same deprecation warning. Would you please let me know that how i can get latest build.

**Comment by sankalpsingha** [comment]
Yup.. Same here.. Still getting the deprecation warnings. Hate to see the yellow warnings screaming in the console.

**Comment by 2468ben** [comment]
Until this is fixed, add this file to hide the deprecations (of course this only works until Ember 3.0, whenever that is):

```javascript
// app/initializers/deprecations.js
import Em from 'ember';

export function initialize(application) {
  Em.Debug.registerDeprecationHandler((message, options, next) => {
    if (options.id === 'ember-application.injected-container') {
      return;
    }
    next(message, options);
  });
}

export default {
  name: 'deprecations',
  initialize
};
```

**Comment by seawatts** [comment]
@2468ben Thanks, that worked =) I thought you could turn it off in a feature flag `ember-debug-handlers` https://github.com/emberjs/rfcs/pull/65 but I guess not.

**Comment by kylenathan** [comment]
Try using https://github.com/mixonic/ember-cli-deprecation-workflow to manage your deprecations

**Comment by 2468ben** [comment]
@kylenathan yeah the only reason it didn't work for me is because I manually set EmberApp.tests = false for my dev environment. If you're not disabling tests in dev, then that plugin should work great.

**Comment by rileyrileyrose** [comment]
This was marked as closed, but I'm still getting deprecation warning... ?

**Comment by marcoow** [comment]
Are you actually using ESA 1.1.0-beta.1?

**Comment by Turbo87** [comment]
@marcoow would it be possible to backport the fix to v1.0 and do a patch release?

**Comment by marcoow** [comment]
In theory yes but I don't actually think it's necessary as it's only a deprecation and we're not even close to Ember 3.0 which would be the first Ember release where this would actually turn into a real problem.

**Comment by Turbo87** [comment]
that's true, but the deprecations are quite annoying :wink: 

I've just installed the addon mentioned by @kylenathan and hope that will bring me some silence on the console, but it's certainly best for the average user to just fix such deprecations.

**Comment by marcoow** [comment]
You can always install 1.1.-beta.1 of course

**Comment by adam-knights** [comment]
We've been running with 1.1 beta since it was released, no changes were required and it works perfectly.

**Comment by tschoartschi** [comment]
As @marcoow pointed out, they are only ```deprecation warnings```. Of course they are annoying but I rather have deprecation warnings than installing a beta. So I'll wait until 1.1 becomes stable :+1:

**Comment by marcoow** [comment]
This is actually fixed in 1.1.0-beta.1
